import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "@/components/Nav/Nav";
import "./globals.css";
import Menu from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });
export const apercuFont = localFont({
  src: [
    {
      path: './ApercuMonoProRegular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './ApercuMonoProMedium.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './ApercuMonoProBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './ApercuMonoProLight.ttf',
      weight: '200',
      style: 'normal',
    },
  ],
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={apercuFont.className}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
